# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

homepage:
    path: /
    controller: App\Controller\DefaultController::index

app_register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: [GET, POST]

app_login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: [GET, POST]

# API routes
api_tags_search:
    path: /api/tags
    controller: App\Controller\ApiController::searchTags
    methods: [GET]

# Recommendation routes
app_recommendations_create:
    path: /recommendations
    controller: App\Controller\RecommendationController::create
    methods: [POST]

app_recommendations_list:
    path: /recommendations/list
    controller: App\Controller\RecommendationController::list
    methods: [GET]

# Handle Chrome DevTools and other .well-known requests
well_known:
    path: /.well-known/{path}
    controller: App\Controller\DefaultController::wellKnown
    requirements:
        path: ".+"
    methods: [GET, HEAD]
